version: "3"

services:
  web:
    image: monimage
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbit
    networks:
      - monreseau

  rabbit:
    image: rabbitmq
    hostname: rabbit
    command: rabbitmq-server
    expose:
      - "5672"

    networks:
      - monreseau


  celery:
    build: .
    command: celery -A projet worker -l INFO
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//
    depends_on:
      - rabbit



networks:
  monreseau:

